[package]
name = "herman"
description = "A daemon that watches folders and organises them automatically."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.0.1"
